# Generated by Django 4.1.3 on 2023-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_content_article_alter_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='Text',
        ),
        migrations.AlterField(
            model_name='content',
            name='Article',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
