# Generated by Django 4.1.3 on 2023-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_remove_content_text_alter_content_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Document',
            field=models.FileField(blank=True, default=' ', upload_to='DocsContant'),
        ),
        migrations.AlterField(
            model_name='content',
            name='Image',
            field=models.ImageField(blank=True, default=' ', upload_to='Imagecontant'),
        ),
    ]
