# Generated by Django 4.1.3 on 2023-07-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_alter_content_document_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Article',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
