# Generated by Django 4.1.3 on 2023-07-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_content_contact_no_alter_content_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='Image',
            field=models.ImageField(default='  ', upload_to='Imagecontant'),
        ),
    ]
