# Generated by Django 4.1.3 on 2023-07-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_alter_content_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='Contact_no',
        ),
        migrations.RemoveField(
            model_name='content',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='content',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='content',
            name='Gender',
        ),
    ]
