# Generated by Django 4.1.3 on 2023-07-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_alter_content_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='Document',
            new_name='video',
        ),
    ]
